#!/usr/bin/env bash
#Bash script that displays:

#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

function handle_sigterm {
	echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

con=1
while [[ ${con} -eq 1 ]]
do
	echo "To infinity and beyond"
	sleep 2
done
