#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for i in {1..100}
do
        if ! ((${i} % 5)) && ! ((${i} % 3)) ; then
                echo "FizzBuzz"
        elif ((${i} % 5)) ; then
                echo "Buzz"
        elif ((${i} % 3)) ; then
                echo "Fizz"
        else
                echo ${i}
        fi
done

