#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.

sudo cp /etc/hosts /etc/hosts.new
sudo sed -i s/127.0.0.1/127.0.0.2 /etc/hosts.new
sudo echo "8.8.8.8	facebook.com" >> /etc/hosts.new
sudo cp -f /etc/hosts.new /etc/hosts
